<?php

namespace rootedit\core;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-08-21 at 11:08:12.
 */
class HttpMessageTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var HttpMessage
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new HttpMessage;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers rootedit\core\HttpMessage::getBody
     * @todo   Implement testGetBody().
     */
    public function testGetBody() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    
}
