<?php

namespace rootedit\core;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-08-21 at 11:09:32.
 */
class OutputTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Output
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Output;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    
    public function testInstance () {
        $this->assertNotNull($this->object);
    }
    
    public function testWithBody() {
        $obj = $this->object->withBody(new dummyStream());
         $this->assertNotNull($obj);
        
    }

  

}

class dummyStream  implements \Psr\Http\Message\StreamInterface{

    function __construct() {
        
    }

    public function __toString() {
        
    }

    public function close() {
        
    }

    public function detach() {
        
    }

    public function eof() {
        
    }

    public function getContents() {
        
    }

    public function getMetadata($key = null) {
        
    }

    public function getSize() {
        
    }

    public function isReadable() {
        
    }

    public function isSeekable() {
        
    }

    public function isWritable() {
        
    }

    public function read($length) {
        
    }

    public function rewind() {
        
    }

    public function seek($offset, $whence = SEEK_SET) {
        
    }

    public function tell() {
        
    }

    public function write($string) {
        
    }

}