<?php
namespace rootedit\core;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-08-21 at 11:06:20.
 */
class ViewStreamWrapperTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ViewStreamWrapper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ViewStreamWrapper(new View());
    }
    
    public function testConstruct() {
        $this->assertNotNull($this->object);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

   
}
