<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-08-21 at 06:59:10.
 */
class ViewTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Dummy
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->view = new rootedit\core\View();
    }

    public function testTemplate() {
        $this->view->setView('#', 'tpl.phtml');
        ob_start();
        $this->view->render();
        $output = ob_get_clean();
        $this->assertEquals('123', $output);
    }

    public function testTemplateWithSlot() {
        $this->view->setView('#', 'tpl.phtml');
        $this->view->slot1 = 'hello';
        $this->view->slot2 = 'world';
        ob_start();
        $this->view->render();
        $output = ob_get_clean();
        $this->assertEquals('1hello2world3',$output);
    }

    public function testTemplateWithTemplate() {
        $this->view->setView('#', 'tpl.phtml');
        $this->view->setView('slot2', 'tpl.phtml');
        $this->view->slot1 = 'hello';
        ob_start();
        $this->view->render();
        $output = ob_get_clean();
        $this->assertEquals( '1hello21hello233',$output);
    }

    public function testJSON() {
        $data = json_encode(['var' => 1, 'var' => 2]);
        $this->view->slot1 = $data;
        ob_start();
        $this->view->render();
        $output = ob_get_clean();
        $this->assertEquals($output, $data);
    }


}
